---
# tasks file for .

- name: install packages required for archive processing
  yum:
    name: "{{ yum_archive_packages }}"
    state: installed

- name: get vault binary
  unarchive:
    src: "{{ vault_url }}"
    dest: "{{ vault_install_path }}"
    remote_src: yes

- name: get jenkins pass from vault
  block:
    - copy:
        src: /tmp/vault_token
        dest: /tmp/vault_token

    - shell: cat /tmp/vault_token
      register: vault_token

    - shell: export VAULT_TOKEN=$(cat /tmp/vault_token) && vault read -address="https://{{ vault_server }}:443" -tls-skip-verify -field=password secret/jenkins
      register: jenkins_admin_password1

    - file:
        path: /tmp/vault_token
        state: absent

    - debug:
        msg: "Jenkins password = {{ jenkins_admin_password1.stdout }}"
