---

- name: yum install packages required for archive processing
  yum:
    name: "{{ archive_packages }}"
    state: installed
  when: ansible_os_family == 'RedHat'

- name: apt install packages required for archive processing
  apt:
    name: "{{ archive_packages }}"
    state: installed
  when: ansible_os_family == 'Debian'

- name: get vault binary
  unarchive:
    src: "{{ vault_url }}"
    dest: "{{ vault_install_path }}"
    remote_src: yes
